### ISSUE TITLE
Portability of the new version

### ISSUE THREAD

**Issue by dkolom** [pseudospectators/FLUSI#14]
The new version is much less portable. In the future development I think we should avoid using functions that are only supported by few compilers. It is really annoying to download the new version of FLuSI and suddenly see that it doesn't work.
Do we really have to use iso_fortran_env? If so, please include the module file it in the repository.

**Comment by tommy-engels** [comment]
well, it is there since summer. the motivation was that for the vortexstreet simulation, the number n=nx*ny*nz is larger than the standart integer. therefore the code failed.

I see you already resolved to problem. actually, as you know, integer(kind=8) is not standaridzed and thus compiler dependent. the iso_fortran_stuff was an effort made by other people to increase portability. A pity that some compilers do not have it. 

I'll be more careful in the future. it would be nice to have acces to your machine for testing. I already use gfortran+mpich, ifort+mpich, ifort+openmpi, IBMXL to check. none of these complained

**Comment by malcolmroberts** [comment]
You could use Jenkins to test that it compiles (and the unit tests pass) on a variety of architectures.
