### ISSUE TITLE
basic_file_routines.f90

### ISSUE THREAD

**Issue by dkolom** [pseudospectators/FLUSI#23]
File src/file_io/basic_file_routines.f90 is now empty. Why was it necessary to move its contents somewhere else? Where? Do we need this empty file any longer?

**Comment by tommy-engels** [comment]
you're right - this file is no longer needed.
The routines have been moved to `module_helpers.f90`. As the insect module is supposed to become stand-alone we need to minimize its dependencies and group them together so that transfer to other codes is easier. 
The file `src/file_io/basic_file_routines.f90` contained external routines (without interface and module), hence some compilers require the definition of an explicit interface to use `character(len=*)`

this has to be done anywhere these functions are used and is tedious and error-prone. note still many compilers have trouble with different-length strings (which is why we have `strlen=120` in `vars.f90`).
After some crashes, I thought it would be better to combine the functions with `module_helpers.90`.

I deleted the empty file.
